spring.application.name=dp-dev


spring.datasource.url=jdbc:postgresql://localhost:5432/dp_pizza_db
spring.datasource.username=dp_play
spring.datasource.password=dp_play_w333


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true